### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by RaptaG** [libredeb/comice-control-center#4]
I'm not on comiceOS, I'm on EndeavourOS, I got all the depedancies installed but I get this:
```python
Traceback (most recent call last):
  File "/home/username/.local/bin/comice-control-center", line 8, in <module>
    from comicecontrolcenter.widgets.connection_box import ConnectionsBox
ModuleNotFoundError: No module named 'comicecontrolcenter'
```
Any help (please?)

**Comment by libredeb** [comment]
> I'm not on comiceOS, I'm on EndeavourOS, I got all the depedancies installed but I get this:
> 
> ```python
> Traceback (most recent call last):
>   File "/home/username/.local/bin/comice-control-center", line 8, in <module>
>     from comicecontrolcenter.widgets.connection_box import ConnectionsBox
> ModuleNotFoundError: No module named 'comicecontrolcenter'
> ```
> 
> Any help (please?)

Can you download the new changes and follow the instructions in the README.md file and confirm if the issue persist? Remember, the python version must be 3.x
